language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

matrix:
    allow_failures:
        - php: hhvm

install:
  - composer update --dev --prefer-source $PREFER_LOWEST

script:
  - ./vendor/bin/phpunit
